version: "3"

services:
  postgres:
    image: postgres
    container_name: iluvcoffee-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgres}
      POSTGRES_DB: ${DATABASE_NAME:-postgres}
    ports:
      - "5432:5432"
